### ISSUE TITLE
Everything starter text truncated - especially launch actions tab.  Cannot resize with mouse.

### ISSUE THREAD

**Issue by enigma9o7** [hippytaffer/bodhi-visa-versa#14]
Text is truncated with no way to resize the box to make the text readable.  

![2021-03-09-083529](https://user-images.githubusercontent.com/30579733/110505928-78da3600-80b3-11eb-8b95-805c9ff365f5.png)

Possible fix: reduce font size by one and eliminate elipses [but make sure regular start menu not affected.]

Possible fix: allow box to resize so user can make it big enough to fit the text

Possible fix: eliminate ellipses and abbreviate actions so the text fits

Or implement all three.

**Comment by thewaiter** [comment]
Have you checked the same situation with default theme? 
Have you checked the Everything config settings? There are plenty size setting in there

Stefan

**Comment by enigma9o7** [comment]
Thank you, I had not checked the everything config settings, and indeed it is possible to resize the box, but unfortunately even turning up all values to maximum doesn't prevent text truncation.  Although does make me think it would be good to increase the size the default value size of that box, or enable mouse resize if its not difficult.

Note same launcher tab as above, with all values maxed out.
![shot-2021-03-20_14-50-47](https://user-images.githubusercontent.com/30579733/111886605-2be84080-898c-11eb-8871-c85bb9ed2e10.png)


I didn't check default theme but I wouldn't be surprised if it has the same issue, I know I've seen it in other themes I've used before and reported on discord.  But right now I'm testing vice-versa straight from repo and trying to document any issues I can find...

**Comment by enigma9o7** [comment]
Štefan has made a scale setting for everything starter that should resolve the truncated text when set to same value as moksha scale factor!   So this may resolve itself outside the theme.  I suspect the resize with mouse is probably related to Moksha too.

**Comment by enigma9o7** [comment]
I'm gunna close this.   Cannot resize with mouse still exists, but this I believe is a moksha issue, not a theme issue.

And the changes to moksha already allow one to prevent text truncation at any scale, and now can resize to almost any size in setting panel, so good enough.
