### ISSUE TITLE
gadgets cannot move to far right end of shelf

### ISSUE THREAD

**Issue by enigma9o7** [hippytaffer/bodhi-visa-versa#2]

**Comment by enigma9o7** [comment]
I have an earlier test version installed in a virtual machine that doesnt have this issue, but current version on my real machine does.

**Comment by thewaiter** [comment]
I fixed this issue some days ago. Not sure why does not work

**Comment by hippytaffer** [comment]
I'm not experiencing this in VM with BL6.0 - can not replicate to fix

**Comment by enigma9o7** [comment]
User error!  I had the shelf set to left orientation.  When setting to middle orientation it works.
