### ISSUE TITLE
Selecting "Borderless" Checkbox leaves a thin border.

### ISSUE THREAD

**Issue by enigma9o7** [hippytaffer/bodhi-visa-versa#20]
In the right click menu, is a checkbox for borderless.  This used to work, but testing now on xeyes, which is what I'd used before, it doesnt.    After further investigation, I figured out the "borderless" checkbox is applying "pixel" border.   

So suggestions to fix: Obvious fix is make borderless be borderless, or change the word to say "Window Outline" or something.  But borderless is the most useful.   If we want pixel border on that right click menu too, add it separately, but don't break borderless!

![Screenshot from 2021-05-02 07-58-42](https://user-images.githubusercontent.com/30579733/116817771-e2f3e200-ab1c-11eb-9d4a-868e94ebfe0f.png)

![Screenshot from 2021-05-02 07-59-47](https://user-images.githubusercontent.com/30579733/116817770-e1c2b500-ab1c-11eb-9a70-9e44373f1ae0.png)

![Screenshot from 2021-05-02 08-02-23](https://user-images.githubusercontent.com/30579733/116817767-df605b00-ab1c-11eb-8e83-396684454195.png)

Also note https://github.com/hippytaffer/bodhi-visa-versa/issues/17 where ryan noted some of the other borders not behaving as described also.

**Comment by thewaiter** [comment]
Needs some investigation

**Comment by thewaiter** [comment]
Yes, you are right
Fix commitet to moksha

thx :)
