### ISSUE TITLE
GTK Theme Makes apps unusable

### ISSUE THREAD

**Issue by enigma9o7** [hippytaffer/bodhi-visa-versa#5]
https://cdn.discordapp.com/attachments/274709215686295562/816102147254648882/shot-2021-03-01_16-18-07.png

https://cdn.discordapp.com/attachments/274709215686295562/816165553928536064/2021-03-01-203011.png

lxtask, dconf editor, libreoffice calc

**Comment by thewaiter** [comment]
Can we consider this issue as closed?

**Comment by enigma9o7** [comment]
Much better, but observed one issue today.... the veritcal scroll bar in leafpad.

**Comment by enigma9o7** [comment]
the_waiter made a fix, should be good now!  closed by his request.
